### ISSUE TITLE
Consider using a gender-neutral alternative to "greybeard"?

### ISSUE THREAD

**Issue by timwis** [AntJanus/programmers-proverbs#56]
Hi, cool list! Saw it come up in my github feed. Just wanted to ask if you'd consider using a gender-neutral alternative to "greybeard" to convey mastery? Just because it's one of those terms that accidentally excludes half the population :/ For example, "wizened master" or even "master." If so, let me know the preferred term and I'm happy to submit a PR for it. Thanks for your consideration :)

**Comment by AntJanus** [comment]
@timwis I'm totally for it! I'm not sure what the best alternative would be and I'd like to avoid `master`. Any other ideas? 

I like the `wizened` part so maybe `Even a wizened engineer will drop production DB`? 

@otlet not a joke! I actually appreciate more gender-neutral/inclusive language.
